// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_eBA529WAlS_6VWf_MDJidGS-xBYtLsM',
    appId: '1:5268409579:web:52050d444acdac5f9a82ae',
    messagingSenderId: '5268409579',
    projectId: 'kitapsat-8c34a',
    authDomain: 'kitapsat-8c34a.firebaseapp.com',
    storageBucket: 'kitapsat-8c34a.firebasestorage.app',
    measurementId: 'G-6J1VYWWMR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7jUrlwBBntvsPhe7ct7WJMYhGzh7IP18',
    appId: '1:5268409579:android:b40dd54ac33dff2f9a82ae',
    messagingSenderId: '5268409579',
    projectId: 'kitapsat-8c34a',
    storageBucket: 'kitapsat-8c34a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-2zpNpgNgpGsITbPJ4GmeCF8SSgMX9Sg',
    appId: '1:5268409579:ios:893b49d46ff70d629a82ae',
    messagingSenderId: '5268409579',
    projectId: 'kitapsat-8c34a',
    storageBucket: 'kitapsat-8c34a.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-2zpNpgNgpGsITbPJ4GmeCF8SSgMX9Sg',
    appId: '1:5268409579:ios:893b49d46ff70d629a82ae',
    messagingSenderId: '5268409579',
    projectId: 'kitapsat-8c34a',
    storageBucket: 'kitapsat-8c34a.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_eBA529WAlS_6VWf_MDJidGS-xBYtLsM',
    appId: '1:5268409579:web:ac66aec90c356a9a9a82ae',
    messagingSenderId: '5268409579',
    projectId: 'kitapsat-8c34a',
    authDomain: 'kitapsat-8c34a.firebaseapp.com',
    storageBucket: 'kitapsat-8c34a.firebasestorage.app',
    measurementId: 'G-V756JT0H9M',
  );

}